modified README

diff --git a/deployogi b/deployogi
--- a/deployogi
+++ b/deployogi
@@ -38,17 +38,18 @@ VERSION="0.1"
 VERSIONFANCY="$C_WHITE v$VERSION$C_GREEN @ https://github.com/coderofsalvation/deployogi$C_RESET"
 REALPATH="$( dirname "$(readlink -f "$0")" )"
 TRIGGERDIR=""
-MICROLOGFILE="/tmp/deployogi.$(date +"%Y%m%d%H%M").log"
+UID="$(date +"%Y%m%d%H%M")"
+CURRENTDIRLOGFILE="/tmp/deployogi.$UID.currentdir"
+MICROLOGFILE="/tmp/deployogi.$UID.log"
 DEPLOY_LOG="deploystart"
 TRIGGERS=(10-on.begin 20-on.backup 30-on.merge 40-on.configure 50-on.generatedocs 60-on.test 70-on.exit )
 REQUIREMENTS=(git)
-CURRENTDIR=""
 USE_SQL=1
 USE_CLONE=1
 IS_CLONE=0
 
 # template files (folded in vim for convenience)
-TPL_TRIGGER="#!/bin/bash\n\n# nothing happening here..yet\n\n# [[ \$IS_CLONE ]] && echo '$0 applied on clone!'\n\n# return > 0 if something went wrong and deployment should stop\nreturn 0"#}}}
+TPL_TRIGGER="#!/bin/bash\n\n# nothing happening here..yet\n\n# [[ \$IS_CLONE ]] && echo '$0 applied on clone!'\n# [[ \$DEPLOYHALT ]] && echo 'deployment was halted, handy for on.exit-hook';\n\n\n# return > 0 if something went wrong and deployment should stop\nreturn 0"
 TPL_CONFIG='#!/bin/bash
 
 # mandatory
@@ -78,22 +79,29 @@ WEBDOMAIN="your.domain.com"                               # domain where the web
 '
   
 # parse config of project if any
-if [[ -f "deployogi.d/config" ]]; then source "deployogi.d/config"; else echo "deployogi.d/config file not found" && exit 1; fi;
+if [[ -f "deployogi.d/config" ]]; then source "deployogi.d/config"; fi; #; else echo "deployogi.d/config file not found" && exit 1; fi;
 
 # catch exit 
 trapped=1;
-trap "_onexit" EXIT SIGINT SIGTERM ERR 0 1
 
 _print(){
   printf "$C_GREEN[deployogi]$C_RESET $1\n"
 }
  
 _onexit(){
+  trap - 1 2 3 15 # clear trap so we are not triggered twice
   trigger="$TRIGGERDIR/deployogi.d/70-on.exit"
   if [[ {$#TRIGGERDIR} != 0 ]]; then 
-    cd "$TRIGGERDIR"
-    _deploytrigger "exiting deployment.." "70-on.exit" 
+    export MICROLOGFILE;  # lets give the subshells access to these variables
+    export DEPLOYLOGFILE; #
+    export DEPLOYHALT;    #
+    (
+      cd "$TRIGGERDIR"
+      _deploytrigger "exiting deployment.." "70-on.exit" || return 1 
+    ) | while read line; do echo -e "$line"; echo -e "$line" >> "$DEPLOYLOGFILE"; done # tee doesnt support colors and create bufferproblems
   fi 
+  echo "[x] summary: $(cat "$MICROLOGFILE")" >> "$DEPLOYLOGFILE"
+  return 0
 }
 
 _checkrequirements(){
@@ -110,6 +118,7 @@ _microlog(){
 
 #                       <-- starts deployment of webapplication (usually called by git hook)
 deploy(){
+  trap "_onexit" EXIT SIGINT SIGTERM ERR 0 1
   :>"$DEPLOYLOGFILE" && chmod 777 "$DEPLOYLOGFILE" # empty and initialize logfile
   [[ ! -d "deployogi.d" ]] && echo "deployogi.d directory not found in $dir, please use init or think things over" && exit 1
   TRIGGERDIR="$(pwd)/deployogi.d" 
@@ -123,10 +132,10 @@ deploy(){
     if [[ $USE_CLONE ]]; then
       _header "clone deployment"
       IS_CLONE=1
-      if [[ $USE_SQL ]]; then _clonedb "$SQL_DB_CLONE"; fi # create a testdatabase (and insert the current backup into it)
+      [[ $USE_SQL ]] && [[ $SQL_DB_CLONE ]] && _clonedb "$SQL_DB_CLONE"; # create a testdatabase (and insert the current backup into it)
       _clonewebapp || _haltdeploy
       _print "entering $PROJECTDIR_CLONE"
-      CURRENTDIR="$PROJECTDIR_CLONE"
+      _setcurrentdir "$PROJECTDIR_CLONE"
       _deployapp "clone version" || _haltdeploy # halt if clone deployment went wrong
       if [[ $USE_SQL ]]; then _dbdiff "$PROJECTDIR_CLONE"; fi 
       unset IS_CLONE
@@ -135,15 +144,20 @@ deploy(){
     printf "\n\n$C_YELLOW[!] about to do the real deployment in 10 secs..press ctrl-c to abort$C_RESET\n"
     for ((i=0; i < 10; i++ )); do printf "."; sleep 1s; done;
     _header "real deployment"
-    CURRENTDIR="$PROJECTDIR"
+    _setcurrentdir "$PROJECTDIR"
     _deployapp "live version" || _haltdeploy # halt if deployment went wrong 
     if [[ $USE_SQL ]]; then _dbdiff "$PROJECTDIR"; fi 
     _microlog "done..deployment went fine \o/!"
-  ) | while read line; do printf "$line\n"; printf "$line\n" >> "$DEPLOYLOGFILE"; done # tee doesnt support colors and create bufferproblems
-  sed -i -r "s:\x1B\[[0-9;]*[mK]::g" "$DEPLOYLOGFILE" # remove colors
+  ) | while read line; do echo -e "$line"; echo -e "$line" >> "$DEPLOYLOGFILE"; done # tee doesnt support colors and create bufferproblems
+  sed -i -r "s:\x1B\[[0-9;]*[mK]::g" "$DEPLOYLOGFILE" # remove colors from deploylogfile
+}
+
+_setcurrentdir(){
+  printf "$1" > "$CURRENTDIRLOGFILE" # because on.exit runs outside of triggerfilescope
 }
 
 _haltdeploy(){
+  DEPLOYHALT=1
   _microlog "something went wrong..halting deployment" 
   cat "$MICROLOGFILE"
   exit 1
@@ -172,7 +186,7 @@ _deploytrigger(){
   trigger="$TRIGGERDIR/$triggerfile"; 
   printf "$C_GREEN[deployogi] %-40s $C_RESET @ $trigger\n" "$desc"
   if [[ -f "$trigger" ]]; then 
-    cd $CURRENTDIR;
+    cd "$(cat "$CURRENTDIRLOGFILE")"
     source "$trigger" 2>&1 || _haltdeploy # while read line; do printf "[x]    | $line\n"; done || _haltdeploy
   else
     _print "$triggerfile not found :("
@@ -192,7 +206,7 @@ _clonewebapp(){
 _checkconfig(){
   _print "checking config"
   vars=(NAME GITDIR PROJECTDIR BACKUPFILE DEPLOYLOGFILE WEBDOMAIN); for var in "${vars[@]}"; do if [[ ! ${!var} ]]; then echo "configfile has missing variable: $var" && exit 1; fi; done  
-  vars=(PROJECTSQL SQL_LOGIN SQL_PW SQL_DB SQL_DB_CLONE); for var in "${vars[@]}"; do [[ ! ${!var} ]] && unset USE_SQL; done
+  vars=(PROJECTSQL SQL_LOGIN SQL_PW SQL_DB); for var in "${vars[@]}"; do if [[ ! ${!var} ]]; then echo "missing $var, so not using SQL features" && unset USE_SQL;  fi; done
   [[ ! -n "$PROJECTDIR_CLONE" ]] && unset USE_CLONE
   printf "[deployogi] using SQL: " && [[ $USE_SQL ]] && printf "yes\n" || printf "$C_YELLOW no (see config)$C_RESET\n"
   printf "[deployogi] deploying on clone before doing the real thing: " && [[ $USE_CLONE ]] && printf "yes\n" ||  printf "$C_YELLOW no (see config)$C_RESET\n"
