modified README

diff --git a/deployogi b/deployogi
--- a/deployogi
+++ b/deployogi
@@ -39,7 +39,7 @@ VERSIONFANCY="$C_WHITE v$VERSION$C_GREEN @ https://github.com/coderofsalvation/d
 REALPATH="$( dirname "$(readlink -f "$0")" )"
 TRIGGERDIR=""
 DEPLOY_LOG="deploystart"
-TRIGGERS=(10-on.begin 20-on.backup 30-on.begin 40-on.merge 50-on.configure 60-on.generatedocs 70-on.test 80-on.exit )
+TRIGGERS=(10-on.begin 20-on.backup 30-on.merge 40-on.configure 50-on.generatedocs 60-on.test 70-on.exit )
 REQUIREMENTS=(git)
 CURRENTDIR=""
 USE_SQL=1
@@ -77,16 +77,17 @@ WEBDOMAIN="your.domain.com"                               # domain where the web
 '
   
 # parse config of project if any
-[[ -f "deployogi.d/config" ]] && source "deployogi.d/config";
+if [[ -f "deployogi.d/config" ]]; then source "deployogi.d/config"; else echo "deployogi.d/config file not found" && exit 1; fi;
 
 # catch exit 
 trap "_onexit" EXIT SIGINT SIGTERM ERR 0 1
  
 _onexit(){
   if [[ ${#TRIGGERDIR} > 0  ]]; then 
-    trigger="$TRIGGERDIR/deployi.d/80-on.exit"
+    trigger="$TRIGGERDIR/deployi.d/70-on.exit"
     [[ -f "$trigger" ]] && source "$trigger"           # fire 'deployogi.d/on.exit' if any
   fi 
+  exit $1
 }
 
 _checkrequirements(){
@@ -101,6 +102,7 @@ deploy(){
   :>"$DEPLOYLOGFILE" && chmod 777 "$DEPLOYLOGFILE" # empty and initialize logfile
   ( 
     [[ ! -d "deployogi.d" ]] && echo "deployogi.d directory not found in $dir, please use init or think things over" && exit 1
+    TRIGGERDIR=""$(pwd)"/deployogi.d" 
     _header "deployogi"; printf "$VERSIONFANCY\n\n"
     _checkconfig 
     _deploytrigger "beginning deployment" "10-on.begin" || _haltdeploy
@@ -113,7 +115,7 @@ deploy(){
       _clonewebapp || _haltdeploy
       echo "[x] entering $PROJECTDIR_CLONE"
       CURRENTDIR="$PROJECTDIR_CLONE"
-      _deployapp || _haltdeploy # halt if clone deployment went wrong
+      _deployapp "clone version" || _haltdeploy # halt if clone deployment went wrong
       if [[ $USE_SQL ]]; then _dbdiff "$PROJECTDIR_CLONE"; fi 
       unset IS_CLONE
     fi 
@@ -121,20 +123,24 @@ deploy(){
     for ((i=0; i < 10; i++ )); do printf "."; sleep 1s; done;
     _header "real deployment"
     CURRENTDIR="$PROJECTDIR"
-    _deployapp || _haltdeploy # halt if deployment went wrong 
+    _deployapp "live version" || _haltdeploy # halt if deployment went wrong 
     if [[ $USE_SQL ]]; then _dbdiff "$PROJECTDIR"; fi 
   ) | while read line; do printf "$line\n"; printf "$line\n" >> "$DEPLOYLOGFILE"; done # tee doesnt support colors and create bufferproblems
   sed -i -r "s:\x1B\[[0-9;]*[mK]::g" "$DEPLOYLOGFILE" # remove colors
 }
 
-_deployhalt(){
-  echo "$C_RED[x] something went wrong..halting deployment $C_RESET"
+_haltdeploy(){
+  printf "hoi"
+  printf "\n$C_GREEN[x] something went wrong..halting deployment $C_RESET"
+  _onexit 1 # continue to on.exit hook
 }
 
 _deployapp(){
-  _deploytrigger "merging latest '$GITBRANCH' on clone" "30-on.merge"
-  _merge
-  _deploytrigger "configuring clone" "40-on.configure"
+  _deploytrigger "merging latest '$GITBRANCH' on $1" "30-on.merge" || _haltdeploy
+  _merge || _haltdeploy
+  _deploytrigger "configuring $1" "40-on.configure" || _haltdeploy
+  _deploytrigger "generating docs for $1" "50-on.generatedocs" || _haltdeploy
+  _deploytrigger "running tests of $1" "60-on.test" || _haltdeploy
 }
 
 _dbdiff(){
@@ -149,11 +155,13 @@ _deploytrigger(){
   triggerfile="$2"
   function="$3"
   [[ -n "$3" ]] && eval $function
-  printf "$C_GREEN[x] %-40s $C_RESET @ $TRIGGERDIR/deployogi.d/$triggerfile\n" "$desc"
-  trigger="$TRIGGERDIR/deployi.d/{$trigger}"; 
+  trigger="$TRIGGERDIR/$triggerfile"; 
+  printf "$C_GREEN[x] %-40s $C_RESET @ $trigger\n" "$desc"
   if [[ -f "$trigger" ]]; then 
     cd $CURRENTDIR;
-    source "$trigger" 2>&1 | while read line; do printf "[x]    | $line\n"; done
+    source "$trigger" 2>&1 || _haltdeploy # | while read line; do printf "[x]    | $line\n"; done || _haltdeploy
+  else
+    echo "[x] $trigger not found"
   fi
 }
 
@@ -168,7 +176,7 @@ _clonewebapp(){
 
 _checkconfig(){
   echo "[x] checking config"
-  vars=(NAME GITDIR PROJECTDIR BACKUPFILE DEPLOYLOGFILE DOMAIN); for var in "${vars[@]}"; do [[ ${!var} ]] || echo "configfile is missing variable: $var"; done  
+  vars=(NAME GITDIR PROJECTDIR BACKUPFILE DEPLOYLOGFILE WEBDOMAIN); for var in "${vars[@]}"; do if [[ ! ${!var} ]]; then echo "configfile has missing variable: $var" && exit 1; fi; done  
   vars=(PROJECTSQL SQL_LOGIN SQL_PW SQL_DB SQL_DB_CLONE); for var in "${vars[@]}"; do [[ ! ${!var} ]] && unset USE_SQL; done
   [[ ! -n "$PROJECTDIR_CLONE" ]] && unset USE_CLONE
   printf "[x] using SQL: " && [[ $USE_SQL ]] && printf "yes\n" || printf "$C_YELLOW no (see config)$C_RESET\n"
@@ -187,7 +195,7 @@ _merge(){
     #git fetch origin              # make sure we have the latest source from our gitrepo ($GITDIR)..note: we dont use pull, since that automatically 
     #git merge origin "$GITBRANCH" # lets merge the new version on top of our old one
     
-  ) 2>&1 | while read line; do printf "[x] git> $line\n"; done
+  ) 2>&1 | while read line; do printf "[x]    | git> $line\n"; done
 
   return $?
 }
